# Site settings
title: Rüne
email: hello@pablorevuelta.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://prevuelta.github.io/jekyll-mustache" # the base hostname & protocol for your site
github_username:  prevuelta

# Build settings
markdown: kramdown
destination: ../build
exclude:
  - assets/javascripts/bower_components
# assets:
   # js_compressor: uglifier